FROM golang:1.23-alpine

WORKDIR /app

# Install reflex for hot reloading
RUN go install github.com/cespare/reflex@v0.3.1

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 10000

# Use reflex to watch for file changes and restart the application
CMD ["reflex", "-r", "\\.go$", "-s", "--", "go", "run", "cmd/api/main.go"]
